import { ComponentType } from "react";
import { MuscleTypeKey } from "@/types";
import {
  FrontBodyExternalOblique,
  FrontBodyPectoralisMajor,
  FrontBodyRectusAbdominis,
  FrontBodyTrapezius,
  FrontLeftArmBiceps,
  FrontLeftArmBrachialis,
  FrontLeftArmBrachioradialis,
  FrontLeftArmDeltoid,
  FrontLeftArmPronatorTeres,
  FrontLeftArmRotatorcuff,
  FrontLeftArmSerratusAnterior,
  FrontLeftArmTriceps,
  FrontLeftLegAdductorLongus,
  FrontLeftLegAdductorMagnus,
  FrontLeftLegExtensorDigitorumBrevis,
  FrontLeftLegExtensorDigitorumLongus,
  FrontLeftLegGracilis,
  FrontLeftLegIliacus,
  FrontLeftLegIliotibialBand,
  FrontLeftLegLateralGastrocnemius,
  FrontLeftLegMedialGastrocnemius,
  FrontLeftLegPeroneusBrevis,
  FrontLeftLegPsoasMajor,
  FrontLeftLegPubicus,
  FrontLeftLegSartorius,
  FrontLeftLegSoleus,
  FrontLeftLegTensorFasciaeLatae,
  FrontLeftLegTeresMajor,
  FrontLeftLegTibialisAnterior,
  FrontRightArmBiceps,
  FrontRightArmBrachialis,
  FrontRightArmBrachioradialis,
  FrontRightArmDeltoid,
  FrontRightArmPronatorTeres,
  FrontRightArmRotatorcuff,
  FrontRightArmSerratusAnterior,
  FrontRightArmTriceps,
  FrontRightLegAdductorLongus,
  FrontRightLegAdductorMagnus,
  FrontRightLegExtensorDigitorumBrevis,
  FrontRightLegExtensorDigitorumLongus,
  FrontRightLegGracilis,
  FrontRightLegIliacus,
  FrontRightLegIliotibialBand,
  FrontRightLegLateralGastrocnemius,
  FrontRightLegMedialGastrocnemius,
  FrontRightLegPeroneusBrevis,
  FrontRightLegPsoasMajor,
  FrontRightLegPubicus,
  FrontRightLegSartorius,
  FrontRightLegSoleus,
  FrontRightLegTensorFasciaeLatae,
  FrontRightLegTeresMajor,
  FrontRightLegTibialisAnterior,
  BackBodyLatissimus,
  BackBodyOblique,
  BackBodyQuadratusLumborum,
  BackBodySemitendinosus,
  BackLeftArmBrachioradialis,
  BackLeftArmDeltoid,
  BackLeftArmExtensorCarpiUlnaris,
  BackLeftArmFlexorCarpiRadialis,
  BackLeftArmPalmarisLongus,
  BackLeftArmSupinator,
  BackLeftArmTriceps,
  BackRightArmBrachioradialis,
  BackRightArmDeltoid,
  BackRightArmExtensorCarpiUlnaris,
  BackRightArmFlexorCarpiRadialis,
  BackRightArmPalmarisLongus,
  BackRightArmSupinator,
  BackRightArmTriceps,
  BackLeftLegSoleus,
  BackLeftLegGluteus,
  BackLeftLegGracilis,
  BackLeftLegIliotibialBand,
  BackLeftLegRectusFemoris,
  BackLeftLegSartorius,
  BackLeftLegBicepsFemoris,
  BackLeftLegAdductorMagnus,
  BackRightLegAdductorMagnus,
  BackRightLegBicepsFemoris,
  BackRightLegGluteus,
  BackRightLegGracilis,
  BackRightLegIliotibialBand,
  BackRightLegRectusFemoris,
  BackRightLegSartorius,
  BackRightLegSoleus,
  FrontLeftLegLargeRetirement,
  FrontRightLegLargeRetirement,
} from "@/components/muscleSvg";
import { MuscleSvgProps } from "@/components/muscleSvg/muscleSvgProps";

const FrontBody: Record<MuscleTypeKey, ComponentType<MuscleSvgProps>> = {
  EXTERNAL_OBLIQUE: FrontBodyExternalOblique,
  PECTORALIS_MAJOR: FrontBodyPectoralisMajor,
  RECTUS_ABDOMINIS: FrontBodyRectusAbdominis,
  TRAPEZIUS: FrontBodyTrapezius,
};

const FrontLeftArm: Record<MuscleTypeKey, ComponentType<MuscleSvgProps>> = {
  BICEPS: FrontLeftArmBiceps,
  BRACHIALIS: FrontLeftArmBrachialis,
  BRACHIORADIALIS: FrontLeftArmBrachioradialis,
  DELTOID: FrontLeftArmDeltoid,
  PRONATOR_TERES: FrontLeftArmPronatorTeres,
  ROTATORCUFF: FrontLeftArmRotatorcuff,
  SERRATUS_ANTERIOR: FrontLeftArmSerratusAnterior,
  TRICEPS: FrontLeftArmTriceps,
};

const FrontRightArm: Record<MuscleTypeKey, ComponentType<MuscleSvgProps>> = {
  BICEPS: FrontRightArmBiceps,
  BRACHIALIS: FrontRightArmBrachialis,
  BRACHIORADIALIS: FrontRightArmBrachioradialis,
  DELTOID: FrontRightArmDeltoid,
  PRONATOR_TERES: FrontRightArmPronatorTeres,
  ROTATORCUFF: FrontRightArmRotatorcuff,
  SERRATUS_ANTERIOR: FrontRightArmSerratusAnterior,
  TRICEPS: FrontRightArmTriceps,
};

const FrontLeftLeg: Record<MuscleTypeKey, ComponentType<MuscleSvgProps>> = {
  ADDUCTOR_LONGUS: FrontLeftLegAdductorLongus,
  ADDUCTOR_MAGNUS: FrontLeftLegAdductorMagnus,
  EXTENSOR_DIGITORUM_BREVIS: FrontLeftLegExtensorDigitorumBrevis,
  EXTENSOR_DIGITORUM_LONGUS: FrontLeftLegExtensorDigitorumLongus,
  GRACILIS: FrontLeftLegGracilis,
  ILIACUS: FrontLeftLegIliacus,
  ILIOTIBIAL_BAND: FrontLeftLegIliotibialBand,
  SEMIMEMBRANOSUS: FrontLeftLegIliotibialBand,
  LATERAL_GASTROCNEMIUS: FrontLeftLegLateralGastrocnemius,
  MEDIAL_GASTROCNEMIUS: FrontLeftLegMedialGastrocnemius,
  PERONEUS_BREVIS: FrontLeftLegPeroneusBrevis,
  PSOAS_MAJOR: FrontLeftLegPsoasMajor,
  PUBICUS: FrontLeftLegPubicus,
  SARTORIUS: FrontLeftLegSartorius,
  SOLEUS: FrontLeftLegSoleus,
  TENSOR_FASCIAE_LATAE: FrontLeftLegTensorFasciaeLatae,
  TERES_MAJOR: FrontLeftLegTeresMajor,
  TIBIALIS_ANTERIOR: FrontLeftLegTibialisAnterior,
  LARGE_RETIREMENT: FrontLeftLegLargeRetirement,
};

const FrontRightLeg: Record<MuscleTypeKey, ComponentType<MuscleSvgProps>> = {
  ADDUCTOR_LONGUS: FrontRightLegAdductorLongus,
  ADDUCTOR_MAGNUS: FrontRightLegAdductorMagnus,
  EXTENSOR_DIGITORUM_BREVIS: FrontRightLegExtensorDigitorumBrevis,
  EXTENSOR_DIGITORUM_LONGUS: FrontRightLegExtensorDigitorumLongus,
  GRACILIS: FrontRightLegGracilis,
  ILIACUS: FrontRightLegIliacus,
  ILIOTIBIAL_BAND: FrontRightLegIliotibialBand,
  SEMIMEMBRANOSUS: FrontRightLegIliotibialBand,
  LATERAL_GASTROCNEMIUS: FrontRightLegLateralGastrocnemius,
  MEDIAL_GASTROCNEMIUS: FrontRightLegMedialGastrocnemius,
  PERONEUS_BREVIS: FrontRightLegPeroneusBrevis,
  PSOAS_MAJOR: FrontRightLegPsoasMajor,
  PUBICUS: FrontRightLegPubicus,
  SARTORIUS: FrontRightLegSartorius,
  SOLEUS: FrontRightLegSoleus,
  TENSOR_FASCIAE_LATAE: FrontRightLegTensorFasciaeLatae,
  TERES_MAJOR: FrontRightLegTeresMajor,
  TIBIALIS_ANTERIOR: FrontRightLegTibialisAnterior,
  LARGE_RETIREMENT: FrontRightLegLargeRetirement,
};

const BackBody: Record<MuscleTypeKey, ComponentType<MuscleSvgProps>> = {
  LATISSIMUS_DORSI: BackBodyLatissimus,
  OBLIQUE: BackBodyOblique,
  QUADRATUS_LUMBORUM: BackBodyQuadratusLumborum,
  SEMITENDINOSUS: BackBodySemitendinosus,
};

const BackLeftArm: Record<MuscleTypeKey, ComponentType<MuscleSvgProps>> = {
  BRACHIORADIALIS: BackLeftArmBrachioradialis,
  DELTOID: BackLeftArmDeltoid,
  EXTENSOR_CARPI_ULNARIS: BackLeftArmExtensorCarpiUlnaris,
  FLEXOR_CARPI_RADIALIS: BackLeftArmFlexorCarpiRadialis,
  PALMARIS_LONGUS: BackLeftArmPalmarisLongus,
  SUPINATOR: BackLeftArmSupinator,
  TRICEPS: BackLeftArmTriceps,
};

const BackRightArm: Record<MuscleTypeKey, ComponentType<MuscleSvgProps>> = {
  BRACHIORADIALIS: BackRightArmBrachioradialis,
  DELTOID: BackRightArmDeltoid,
  EXTENSOR_CARPI_ULNARIS: BackRightArmExtensorCarpiUlnaris,
  FLEXOR_CARPI_RADIALIS: BackRightArmFlexorCarpiRadialis,
  PALMARIS_LONGUS: BackRightArmPalmarisLongus,
  SUPINATOR: BackRightArmSupinator,
  TRICEPS: BackRightArmTriceps,
};

const BackLeftLeg: Record<MuscleTypeKey, ComponentType<MuscleSvgProps>> = {
  ADDUCTOR_MAGNUS: BackLeftLegAdductorMagnus,
  BICEPS_FEMORIS: BackLeftLegBicepsFemoris,
  GLUTEUS: BackLeftLegGluteus,
  GRACILIS: BackLeftLegGracilis,
  ILIOTIBIAL_BAND: BackLeftLegIliotibialBand,
  SEMIMEMBRANOSUS: BackLeftLegIliotibialBand,
  RECTUS_FEMORIS: BackLeftLegRectusFemoris,
  SARTORIUS: BackLeftLegSartorius,
  SOLEUS: BackLeftLegSoleus,
};

const BackRightLeg: Record<MuscleTypeKey, ComponentType<MuscleSvgProps>> = {
  ADDUCTOR_MAGNUS: BackRightLegAdductorMagnus,
  BICEPS_FEMORIS: BackRightLegBicepsFemoris,
  GLUTEUS: BackRightLegGluteus,
  GRACILIS: BackRightLegGracilis,
  ILIOTIBIAL_BAND: BackRightLegIliotibialBand,
  SEMIMEMBRANOSUS: BackRightLegIliotibialBand,
  RECTUS_FEMORIS: BackRightLegRectusFemoris,
  SARTORIUS: BackRightLegSartorius,
  SOLEUS: BackRightLegSoleus,
};

export const MuscleImgMap: Record<
  string,
  Record<MuscleTypeKey, ComponentType<MuscleSvgProps>>
> = {
  앞_몸통: FrontBody,
  앞_왼팔: FrontLeftArm,
  앞_오른팔: FrontRightArm,
  "앞_왼쪽 다리": FrontLeftLeg,
  "앞_오른쪽 다리": FrontRightLeg,

  뒤_몸통: BackBody,
  뒤_왼팔: BackLeftArm,
  뒤_오른팔: BackRightArm,
  "뒤_왼쪽 다리": BackLeftLeg,
  "뒤_오른쪽 다리": BackRightLeg,
};
