// 근육 타입
export const MuscleType: string[] = [
  "TRAPEZIUS", //"승모근"
  "INFRASPINATUS", //"오훼완근""
  "TRICEPS", //"삼두근""
  "RECTUS_ABDOMINIS", //"복직근""
  "EXTERNAL_OBLIQUE", //"외복사근""
  "ILIACUS", //"장골근""
  "GLUTEUS", //"둔근""
  "TENSOR_FASCIAE_LATAE", //"대퇴근막장근""
  "PSOAS_MAJOR", //"대요근""
  "TERES_MAJOR", //"봉공근""
  "RECTUS_FEMORIS", //"대퇴이두근""
  "SOLEUS", //"박근""
  "MEDIAL_GASTROCNEMIUS", //"내측광근""
  "LATERAL_GASTROCNEMIUS", //"외측광근""
  "PERONEUS_LONGUS", //"중간광근""
  "ILIOTIBIAL_BAND", //"장경인대""
  "TIBIALIS_ANTERIOR", //"전경골근""
  "EXTENSOR_DIGITORUM_LONGUS", //"장지신근""
  "SARTORIUS", //"가자미근""
  "EXTENSOR_DIGITORUM_BREVIS", //"장모지신근""
  "DELTOID", //"삼각근""
  "PECTORALIS_MAJOR", //"대흉근""
  "LATISSIMUS_DORSI", //"광배근""
  "BICEPS", //"이두근""
  "BRACHIALIS", //"상완근""
  "PRONATOR_TERES", //"원회내근""
  "BRACHIORADIALIS", //"완요골근""
  "SERRATUS_ANTERIOR", //"장장근""
  "PUBICUS", //"치골근""
  "ADDUCTOR_LONGUS", //"장내전근""
  "ADDUCTOR_MAGNUS", //"대내전근""
  "GRACILIS", //"비복근""
  "PERONEUS_BREVIS", //"장비골근""
  "FLEXOR_CARPI_RADIALIS", //"주근""
  "PALMARIS_LONGUS", //"척측수근신근""
  "EXTENSOR_CARPI_ULNARIS", //"충지신근""
  "SUPINATOR", //"요측수근신근""
  "OBLIQUE", //"소원근""
  "QUADRATUS_LUMBORUM", //"대원근""
  "SEMITENDINOSUS", //"척추기립근""
  "BICEPS_FEMORIS", //"반건반막양근""
  "SEMIMEMBRANOSUS", //"장경인대""
  "LARGE_RETIREMENT", //"대퇴직근"
] as const;

export type MuscleTypeKey = (typeof MuscleType)[number];
